BUILD_DIR = ../../build

$(BUILD_DIR)/generator.o: src/generator.c inc/generator.h $(BUILD_DIR)/component.o 
	$(CC) -c $< -o $@ $(CFLAGS)

$(BUILD_DIR)/component.o: src/component.c inc/component.h $(BUILD_DIR)/socket.o 
	$(CC) -c $< -o $@ $(CFLAGS)

$(BUILD_DIR)/socket.o: src/socket.c inc/socket.h
	$(CC) -c $< -o $@ $(CFLAGS)

